# Generated by Django 4.2.6 on 2024-06-05 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicActivityInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('Email', 'Email'), ('Call', 'Call'), ('Meeting', 'Meeting'), ('To-Do', 'To-Do')], help_text='Activity Type', max_length=50, null=True)),
                ('assigned_to', models.CharField(help_text='Assigned To', max_length=255, null=True)),
                ('activity_title', models.CharField(help_text='Activity Title', max_length=255, null=True)),
                ('description', models.TextField(help_text='Description', null=True)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], help_text='Status', max_length=20, null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], help_text='Priority', max_length=10, null=True)),
                ('due_date', models.DateField(help_text='Due Date', null=True)),
                ('start_time', models.TimeField(help_text='Start Time', null=True)),
                ('end_time', models.TimeField(help_text='End Time', null=True)),
                ('duration', models.DurationField(help_text='Duration', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(help_text='Organization name', max_length=255, null=True)),
                ('contact_name', models.CharField(help_text='Contact Name', max_length=255, null=True)),
                ('email', models.EmailField(help_text='Email address', max_length=254, null=True)),
                ('phone', models.CharField(help_text='Phone number', max_length=15, null=True)),
                ('requirement', models.TextField(help_text='Requirement details', null=True)),
                ('rating', models.IntegerField(help_text='Rating (e.g., 1, 2, 3)', null=True)),
                ('win', models.CharField(choices=[('Win', 'Win'), ('Lost', 'Lost')], help_text='Win status', max_length=10, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Qualified/Meeting', 'Qualified/Meeting'), ('Proposition', 'Proposition'), ('Completed', 'Completed')], help_text='Lead status', max_length=20, null=True)),
                ('compliance', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], help_text='Compliance status', max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(help_text='Meeting Title', max_length=255, null=True)),
                ('meeting_description', models.TextField(help_text='Meeting Description', null=True)),
                ('meeting_date', models.DateField(help_text='Meeting Date', null=True)),
                ('start_time', models.TimeField(help_text='Start Time', null=True)),
                ('end_time', models.TimeField(help_text='End Time', null=True)),
                ('duration', models.DurationField(help_text='Duration', null=True)),
                ('meeting_type', models.CharField(choices=[('conference call', 'conference call'), ('in-person', 'in-person'), ('virtual', 'virtual')], help_text='Meeting Type', max_length=20, null=True)),
                ('attendees', models.TextField(help_text='Attendees', null=True)),
                ('presenters', models.TextField(help_text='Presenter(s)', null=True)),
                ('activity', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_details', to='crm_app.basicactivityinformation')),
            ],
        ),
        migrations.CreateModel(
            name='EmailSpecificFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(help_text='Sender', max_length=254, null=True)),
                ('recipients', models.TextField(help_text='Recipients', null=True)),
                ('cc', models.TextField(help_text='CC', null=True)),
                ('bcc', models.TextField(help_text='BCC', null=True)),
                ('subject', models.CharField(help_text='Subject', max_length=255, null=True)),
                ('body', models.TextField(help_text='Body', null=True)),
                ('attachments', models.FileField(help_text='Attachments', null=True, upload_to='attachments/')),
                ('sent_date_time', models.DateTimeField(help_text='Sent Date and Time', null=True)),
                ('read_receipt', models.BooleanField(default=False, help_text='Read Receipt', null=True)),
                ('activity', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_details', to='crm_app.basicactivityinformation')),
            ],
        ),
        migrations.AddField(
            model_name='basicactivityinformation',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm_app.lead'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(help_text='Street Address (e.g., 123 Main St)', max_length=255, null=True)),
                ('suite_apartment_unit', models.CharField(help_text='Suite/Apartment/Unit Number', max_length=255, null=True)),
                ('city', models.CharField(help_text='City', max_length=100, null=True)),
                ('state_province', models.CharField(help_text='State/Province', max_length=100, null=True)),
                ('zip_postal_code', models.CharField(help_text='ZIP/Postal Code', max_length=20, null=True)),
                ('country', models.CharField(help_text='Country', max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude', max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude', max_digits=9, null=True)),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='crm_app.lead')),
            ],
        ),
    ]
