# Generated by Django 4.2.16 on 2024-11-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_emailattachment_emailtemplate_leadstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, help_text='Data ID', max_length=40)),
                ('url', models.CharField(blank=True, max_length=8, unique=True)),
                ('Title', models.CharField(blank=True, help_text='Form title', max_length=200)),
                ('enable_Title', models.BooleanField(default=True, help_text='Enable Title field')),
                ('require_Title', models.BooleanField(default=False, help_text='Require Title field')),
                ('Your_name', models.CharField(blank=True, help_text='Your name', max_length=100)),
                ('enable_Your_name', models.BooleanField(default=True, help_text='Enable Your name field')),
                ('require_Your_name', models.BooleanField(default=False, help_text='Require Your name field')),
                ('Email', models.CharField(blank=True, help_text='Your email', max_length=50)),
                ('enable_Email', models.BooleanField(default=True, help_text='Enable Email field')),
                ('require_Email', models.BooleanField(default=False, help_text='Require Email field')),
                ('Phone_number', models.CharField(blank=True, default='', help_text='Your phone number', max_length=50)),
                ('enable_Phone_number', models.BooleanField(default=True, help_text='Enable Phone number field')),
                ('require_Phone_number', models.BooleanField(default=False, help_text='Require Phone number field')),
                ('Organization', models.CharField(blank=True, help_text='Your organization', max_length=50)),
                ('enable_Organization', models.BooleanField(default=True, help_text='Enable Organization field')),
                ('require_Organization', models.BooleanField(default=False, help_text='Require Organization field')),
                ('location', models.CharField(blank=True, help_text='Subject', max_length=50)),
                ('enable_location', models.BooleanField(default=True, help_text='Enable Subject field')),
                ('require_location', models.BooleanField(default=False, help_text='Require Subject field')),
                ('Message', models.CharField(blank=True, help_text='Message', max_length=50)),
                ('enable_Message', models.BooleanField(default=True, help_text='Enable Message field')),
                ('require_Message', models.BooleanField(default=False, help_text='Require Message field')),
                ('inline_Label', models.BooleanField(default=False, help_text='Inline Label of Input Fields')),
                ('style', models.TextField(blank=True, default='', help_text='CSS styling')),
                ('Created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
            ],
            options={
                'verbose_name_plural': 'Contact Form',
            },
        ),
    ]
