# Generated by Django 4.2.6 on 2024-07-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_remove_emailspecificfields_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(default='India', help_text='Country', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='state_province',
            field=models.CharField(blank=True, help_text='State/Province', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='street_address',
            field=models.CharField(blank=True, help_text='Street Address (e.g., 123 Main St)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='suite_apartment_unit',
            field=models.CharField(blank=True, help_text='Suite/Apartment/Unit Number', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='zip_postal_code',
            field=models.CharField(blank=True, help_text='ZIP/Postal Code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Postponed', 'Postponed')], default='Scheduled', help_text='Meeting Status', max_length=20),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
