# Generated by Django 4.2.6 on 2024-07-29 06:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_lead_city_lead_country_lead_latitude_lead_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template Name', max_length=255)),
                ('subject', models.CharField(help_text='Email Subject', max_length=255)),
                ('body', models.TextField(help_text='Email Body')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date and time when the template was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the template was last updated')),
            ],
        ),
        migrations.RemoveField(
            model_name='emailspecificfields',
            name='body',
        ),
        migrations.RemoveField(
            model_name='emailspecificfields',
            name='subject',
        ),
        migrations.AddField(
            model_name='emailspecificfields',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Email Template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='crm_app.emailtemplate'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Email Template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetingemails', to='crm_app.emailtemplate'),
        ),
    ]
