# Generated by Django 4.2.6 on 2024-07-29 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_emailtemplate_remove_emailspecificfields_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='read_receipt',
            field=models.BooleanField(blank=True, default=False, help_text='Read Receipt if mail was sent', null=True),
        ),
        migrations.AlterField(
            model_name='emailattachment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_attachments', to='crm_app.emailtemplate'),
        ),
    ]
