# Generated by Django 4.2.6 on 2024-10-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0009_emailtemplate_template_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailspecificfields',
            name='template',
        ),
        migrations.AddField(
            model_name='emailspecificfields',
            name='body',
            field=models.TextField(blank=True, help_text='Body', null=True),
        ),
    ]
