# Generated by Django 4.2.6 on 2024-08-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0007_rename_updated_at_leadstatus_changed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadstatus',
            name='new_status',
            field=models.CharField(choices=[('New', 'New'), ('Qualified/Meeting', 'Qualified/Meeting'), ('Process', 'In Process'), ('Win', 'Win'), ('Lost', 'Lost')], default='New', help_text='Current lead status', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadstatus',
            name='old_status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Qualified/Meeting', 'Qualified/Meeting'), ('Process', 'In Process'), ('Win', 'Win'), ('Lost', 'Lost')], help_text='Previous lead status', max_length=20, null=True),
        ),
    ]
