# Generated by Django 4.2.6 on 2024-10-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0010_remove_emailspecificfields_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailspecificfields',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='emailspecificfields',
            name='mail_type',
            field=models.CharField(choices=[('welcome', 'Welcome Email'), ('meeting', 'Meeting Email'), ('notification', 'Notification Email'), ('reminder', 'Reminder Email'), ('template', 'Template')], default='template', help_text='Type of Email Template', max_length=50),
        ),
    ]
