# Generated by Django 4.2.6 on 2024-10-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0011_remove_emailspecificfields_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailattachment',
            name='file',
            field=models.FileField(blank=True, help_text='Attachments', null=True, upload_to='attachments'),
        ),
    ]
