# Generated by Django 4.2.16 on 2024-10-18 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0012_alter_emailattachment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('input_suggestion', 'Input Suggestion'), ('error_message', 'Error Message')], default='input_suggestion', max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(blank=True, choices=[('conference-call', 'conference call'), ('in-person', 'in person'), ('virtual', 'virtual')], help_text='Meeting Type', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_leads', models.BooleanField(default=False)),
                ('can_add_leads', models.BooleanField(default=False)),
                ('can_edit_leads', models.BooleanField(default=False)),
                ('can_delete_leads', models.BooleanField(default=False)),
                ('can_view_lead_status', models.BooleanField(default=False)),
                ('can_edit_lead_status', models.BooleanField(default=False)),
                ('can_view_timeline', models.BooleanField(default=False)),
                ('can_create_meeting', models.BooleanField(default=False)),
                ('can_edit_meeting', models.BooleanField(default=False)),
                ('can_view_calendar', models.BooleanField(default=False)),
                ('can_edit_calendar', models.BooleanField(default=False)),
                ('can_send_sms', models.BooleanField(default=False)),
                ('can_view_sms', models.BooleanField(default=False)),
                ('can_view_email', models.BooleanField(default=False)),
                ('can_edit_email', models.BooleanField(default=False)),
                ('can_view_meeting', models.BooleanField(default=False)),
                ('can_view_quotation', models.BooleanField(default=False)),
                ('can_send_mail', models.BooleanField(default=False)),
                ('can_view_mail', models.BooleanField(default=False)),
                ('can_analytics', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='crm_app.profile')),
            ],
        ),
    ]
