# Generated by Django 4.2.16 on 2024-10-21 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0013_textmessage_alter_meeting_meeting_type_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('letterhead_image', models.ImageField(blank=True, null=True, upload_to='letterheads/')),
                ('margin_top', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('margin_left', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('organization', models.CharField(max_length=255)),
                ('template_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quotation Template',
                'verbose_name_plural': 'Quotation Templates',
            },
        ),
        migrations.CreateModel(
            name='QuotationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular_id', models.CharField(max_length=255)),
                ('particular', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('enable', models.BooleanField(default=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('quotation_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_data_entries', to='crm_app.quotationtemplate')),
            ],
            options={
                'verbose_name': 'Quotation Data',
                'verbose_name_plural': 'Quotation Data',
            },
        ),
    ]
