# Generated by Django 4.2.16 on 2024-11-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0016_alter_quotationdata_basic_wages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailattachment',
            old_name='file',
            new_name='name',
        ),
    ]
