# Generated by Django 4.2.16 on 2024-11-06 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm_app', '0018_alter_profile_options_emailtemplate_sender_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_color', models.CharField(blank=True, help_text="The user's preferred theme color (e.g., #FFFFFF for white).", max_length=7, null=True)),
                ('language', models.CharField(default='en', help_text='The preferred language for the user.', max_length=50)),
                ('meeting_notification', models.BooleanField(default=True, help_text='Whether the user wants to receive meeting notifications.')),
                ('self_browser_notification', models.BooleanField(default=True, help_text='Whether the user wants to receive browser notifications.')),
                ('self_sound_notification', models.BooleanField(default=True, help_text='Whether the user wants to receive sound notifications.')),
                ('welcome_mail', models.BooleanField(default=False, help_text='Whether the user has received a welcome email.')),
                ('auto_refresh_duration', models.PositiveIntegerField(default=300, help_text='The duration (in seconds) for auto-refresh, default is 300 seconds (5 minutes).')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
