# Generated by Django 4.2.16 on 2024-11-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0019_alter_permissions_user_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingstatuschangelog',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
