# Generated by Django 4.2.16 on 2024-11-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0020_meetingstatuschangelog_mail_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='state_province',
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_quality',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold'), ('junk', 'Junk')], default='warm', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, default=None, help_text='Additional notes or comments about this lead.', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='secondary_email',
            field=models.EmailField(blank=True, default=None, help_text='Secondary email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='secondary_phone',
            field=models.CharField(blank=True, default=None, help_text='Secondary Phone number', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('referral', 'Referral'), ('ads', 'Ads'), ('social', 'Social Media'), ('other', 'Other')], default='website', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, default=None, help_text='State/Province', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='website',
            field=models.URLField(blank=True, default=None, help_text='The website URL of the lead.', null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, default=None, help_text='City', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='compliance',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], default=None, help_text='Compliance status', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_name',
            field=models.CharField(blank=True, default=None, help_text='Contact Name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='country',
            field=models.CharField(blank=True, default='India', help_text='Country', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, default=None, help_text='Email address', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='organization',
            field=models.CharField(blank=True, default=None, help_text='Organization name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, default=None, help_text='Phone number', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='requirement',
            field=models.TextField(blank=True, default=None, help_text='Requirement details', null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='street_address',
            field=models.CharField(blank=True, default=None, help_text='Street Address (e.g., 123 Main St)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='suite_apartment_unit',
            field=models.CharField(blank=True, default=None, help_text='Suite/Apartment/Unit Number', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='zip_postal_code',
            field=models.CharField(blank=True, default=None, help_text='ZIP/Postal Code', max_length=20, null=True),
        ),
    ]
